### ISSUE TITLE
这玩意怎么用啊

### ISSUE THREAD

**Issue by King-Nameless** [molehzy/GenshinBot#1]
没说明实在不会啊，go-cqhttp下了最新版的，然后选了正向WS连接，启动GenshinBot.exe后，主页的连接没问题，但是设置里刷新不出群，Data里也没有Group.ini，私聊机器人YSHELP会发菜单图，但是YS绑定提示[get_UserGameRolesByCookie] API请求失败,状态码 405，这怎么搞？还是因为设置里的token没填的缘故？如果是的话要填什么啊

**Comment by molehzy** [comment]
~~https://github.com/molehzy/GenshinBot/releases/tag/2021.12.29~~
https://github.com/molehzy/GenshinBot/releases/tag/2021.12.29-2

**Comment by molehzy** [comment]
获取群列表要正向http

**Comment by molehzy** [comment]
写了一版简单说明
https://github.com/molehzy/GenshinBot/wiki/%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E

**Comment by King-Nameless** [comment]
> 写了一版简单说明 https://github.com/molehzy/GenshinBot/wiki/%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E

谢谢
![))@RWP6~BLVM188{I5}`$AO](https://user-images.githubusercontent.com/83447487/147650105-c2561e60-9d5e-432b-83a2-c32fcc1d184d.jpg)
